### ISSUE TITLE
args-out-of-range error

### ISSUE THREAD

**Issue by joe9** [rolandwalker/flyspell-lazy#7]
Hello,

I am seeing the below error. It started manifesting in erc buffers and now it is showing up even when editing shell scripts.

```
Debugger entered--Lisp error: (args-out-of-range #<buffer filename.sh> 704 799)
  buffer-substring-no-properties(799 704)
  byte-code("\306p\211\211\206  flyspell-lazy-check-pending()
  apply(flyspell-lazy-check-pending nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 3 0 t flyspell-lazy-check-pending nil idle 0])
```

Can you please help?

Thanks and Sorry for the bother,

**Comment by joe9** [comment]
Hello Roland Walker,

I am still seeing this issue. I see it occuring while editing haskell source files too.

flyspell-lazy-20141222.652 is the version I am using.

This is the message:
Debugger entered--Lisp error: (args-out-of-range #<buffer Login.hs> 1865 1906)
  buffer-substring-no-properties(1906 1865)
  byte-code("<lot of binary data here>" [inhibit-quit buf buffer flyspell-lazy-buffer-list flyspell-changes flyspell-lazy-hurry-flag nil timerp 0 timer-set-idle-time t 1 input-pending-p add-point match-data ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) 5 40 round 0.5 search-backward-regexp "[[:alpha:]]" search-forward-regexp remove (nil) sort #[(a b) "@	@W\207" [a b] 2] last abs append buffer-substring-no-properties string-match (nil) ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) "[ \n	
\f]" ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) "[[:alpha:]]\\{" format "%s" ",\\}" (nil) (nil) ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) flyspell-lazy-safe-buffer-substring replace-regexp-in-string "[[:punct:]]+" " " "^[ \n	
\f]+" "" "^\\([^ \n	
\f]\\{1,3\\}\\([ \n	
\f]+\\|$\\)\\)+" ...] 8)
  flyspell-lazy-check-pending()
  apply(flyspell-lazy-check-pending nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 3 0 t flyspell-lazy-check-pending nil idle 0])

Thanks
Joe

**Comment by incandescentman** [comment]
I also also experiencing this issue.
